service:
  name: inventory-rest-apis
package:
  individually: true

plugins: 
  - serverless-offline 
  - serverless-domain-manager
  - serverless-deployment-bucket
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x 
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  profile: serverless-admin
  deploymentBucket:
    name: inventory-rest-apis
    serverSideEncryption: AES256
  environment:
    PRODUCT_TABLE_NAME: ${self:custom.ProductTable.name}
  iam: 
   role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:ap-south-1:670022476151:table/Product-dev 
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::${self:custom.InventoryBucket.name}/* 
resources:
  Resources:
    ProductCategoryTable: ${file(infra/resources/dynamodb.yml):ProductCategoryTable}
    ProductTable: ${file(infra/resources/dynamodb.yml):ProductTable}
    InventoryBucket: ${file(infra/resources/s3.yml):InventoryBucket}
    InventoryBucketPolicy: ${file(infra/resources/s3.yml):InventoryBucketPolicy}
    
functions:
  inventoryHealthCheck:
    handler: app/handlers/health.handler
    events:
      - http:
          method: GET
          path: /health
          cors: true  

custom:
  stage: dev 
  webpack: 
    keepOutputDirectory: true
    includeModules:
      packagePath: './package.json'
    webpackConfig: 'webpack.config.js' 
    packager: 'npm'  
    excludeFiles: src/**/*.test.js  

  domains:  
    dev: api.dev.migobucks.com 
  ProductTable:
    name: !Ref ProductTable 
    arn: !GetAtt ProductTable.Arn 
  ProductCategoryTable:
    name: !Ref ProductCategoryTable 
    arn: !GetAtt ProductCategoryTable.Arn 
  InventoryBucket:
    name: inventory-rest-apis-${self:provider.stage}   
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'inventory'
    stage: dev 
    createRoute53Record: true 
  bundle:
    linting: false